<?php
/**
    * Control Crud class
    * @file
    *
    * @package
    * @author Daniel Sum
    * @link 	@endlink
    * @see
    * @description
    *
    * @code

          $controller = new ctrl_table_crud('Your_Table');

          $controller->display();

      @endcode
    * @comments
    * @todo
*/

arx::uses('i18n');

class ctrl_table extends Arx
{

    public $_a, $_table; //variable

    public $_ajax = true;

    public function __construct($table, $c = null)
    {

        parent::__construct();

        if(isset($c['_ajax'])) $this->_ajax = $c['_ajax'];
        // Load CSS & JS
        c_hook::css(array(ARX_CSS.DS.'bootstrap.css', ARX_CSS.DS.'arx.css'));

        c_hook::js(array(ARX_JS.DS.'jquery.js', ARX_JS.DS.'jquery.datatable.js', ARX_JS.DS.'arx.js', '?get=.js'));

        $this->app = new arx();

        $this->_table = a_db::table($table);

        switch (true) {
            case ($_GET['get'] == '.js'):
                die($this->get_js());
                exit;
            break;
            case ($_POST['action'] == 'create'):

            break;
            case ($_POST['action'] == 'read'):

            break;

            case ($_POST['action'] == 'update'):

            break;

            case ($_POST['action'] == 'delete'):

            break;

            default:

            break;
        }

        return $this;

    }

    public function create($type = 'html5')
    {
        return 'okiiiiii';
    }

    public function read($type = 'json')
    {
        return 'okiiiiii';
    }

    public function update($type = 'html5')
    {
        return 'okiiiiii';
    }

    public function delete($type = 'html5')
    {
        return 'okiiiiii';
    }

    public function display($tpl = null, &$app = null)
    {
        if ($app) {
            $app->_body .= $this->fetch(ARX_HELPERS.DS.'table_crud.tpl', array('data'=>$this->_table->find_array()));

            switch (true) {
                case ($tpl != null):
                    $app->tpl->display($tpl);
                break;
                case ($tpl == null):
                    $app->tpl->display(ARX_VIEWS.DS.'html5.tpl');
                break;
            }

        } else {
            $this->_ajax = $this->_ajax;

            //@TODO : query
            $this->_body = $this->fetch(ARX_HELPERS.DS.'table_crud.tpl', array('data'=>$this->_table->find_array()));

            switch (true) {
                case ($tpl != null):
                    $this->tpl->display($tpl);
                break;
                case ($tpl == null):
                    $this->tpl->display(ARX_VIEWS.DS.'html5.tpl');
                break;
            }
        }

    }

    /**
     * Special method to get an autogenerated JS especially for the controller
     *
     * @param $
     *
     * @return
     *
     * @code
     *
     * @endcode
     */
    public function get_js()
    {
        u::header('utf8');
        u::header('js');

        $this->tpl->display(ARX_HELPERS.DS.'table_crud.tpl.js');

        exit;
    }
}
